#pragma once

#import "ScalableCalculatorCOMEvents.tlb" raw_interfaces_only

using namespace ATL;
using namespace ScalableCalculatorCOMEventsLib;

template <class T>
class CProxy_ICalculatorEvents : public IConnectionPointImpl<T, &__uuidof(_ICalculatorEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
	HRESULT Fire_Event(const LONGLONG action_id, const LONGLONG lhs, const LONGLONG rhs)
	{

		HRESULT hr = S_OK;
		T* pThis = static_cast<T*>(this);
		int cConnections = m_vec.GetSize();

		// For every object that connects to the connection points object,
		// call its event receiving function
		for (int iConnection = 0; iConnection < cConnections; iConnection++)
		{
			pThis->Lock();
			CComPtr<IUnknown> punkConnection = m_vec.GetAt(iConnection);
			pThis->Unlock();

			if (punkConnection == NULL) continue;

			CComQIPtr<IDispatch> pConnection = punkConnection.p;

			if (pConnection)
			{
				// Parameters of event receiving function, same as the definition of event function
				CComVariant aVarParams[2];
				aVarParams[0] = rhs;
				aVarParams[0].vt = VT_I2;
				aVarParams[1] = lhs;
				aVarParams[1].vt = VT_I2;

				DISPPARAMS params = { aVarParams, NULL, 2, 0 };

				// Dispid is the id of event function in idl file
				hr = pConnection->Invoke(action_id, IID_NULL, LOCALE_USER_DEFAULT,
					DISPATCH_METHOD, &params, NULL, NULL, NULL);
			}
		}
		return hr;
	}
};