// ScalableCalculatorCOMEvents.idl : IDL source for ScalableCalculatorCOMEvents
//

// This file will be processed by the MIDL tool to
// produce the type library (ScalableCalculatorCOMEvents.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(08760004-aed2-4f9b-9f2d-db519096ca78),
	version(1.0),
]
library ScalableCalculatorCOMLib
{
	typedef enum Events
	{
		EVID_ADD = 1,
		EVID_SUBTRACT = 2,
		EVID_MULTIPLY = 3,
		EVID_DIVIDE = 4,
		EVID_NOTHING = 5
	} Events;

	[
		object,
		uuid(7a11d31a-c3a9-44c3-b34d-fcc218b971c4),
		dual,
		nonextensible,
		pointer_default(unique)
	]
	interface ICalculatorEv : IDispatch
	{
		[id(1)] HRESULT Compute([in] CHAR action, [in] LONGLONG lhs, [in] LONGLONG rhs);
	};

	importlib("stdole2.tlb");
	[
		uuid(2689808c-b645-4b8b-ad4b-38b34f1bc12b)
	]
	dispinterface _ICalculatorEvents
	{
		properties:
		methods:
			[id(EVID_ADD)] void OnAdd([in] const LONGLONG lhs,[in] const LONGLONG rhs);
			[id(EVID_SUBTRACT)] void OnSubtract([in] const LONGLONG lhs,[in] const LONGLONG rhs);
			[id(EVID_MULTIPLY)] void OnMultiply([in] const LONGLONG lhs,[in] const LONGLONG rhs);
			[id(EVID_DIVIDE)] void OnDivide([in] const LONGLONG lhs,[in] const LONGLONG rhs);
			[id(EVID_NOTHING)] void Nothing([in] const LONGLONG lhs,[in] const LONGLONG rhs);
	};

	[
		uuid(86d4af8c-ffdc-4317-b120-bf76fac5cd6f)
	]
	coclass Calculator
	{
		[default] interface ICalculatorEv;
		[default, source] dispinterface _ICalculatorEvents;
	};
};